### PR TITLE
Fix mistype in README

### PR DESCRIPTION
**Pull request by simonenkoi**
Closes: #15

### CODE REVIEW

**Comment by simonenkoi** [comment]
I have "must be at least '0'" message instead of "must be equal or greater than 0". Should I fix it too or am I doing something wrong?

**Comment by nlochschmidt** [comment]
Thanks for your contribution. 

You are right, the README is not completely accurate in that regard. If you could also change the second message that would be nice. I'll merge it in afterwards.

**Comment by simonenkoi** [comment]
Done. Thank you for your work. It's really awesome.
JFYI, I've merged integration for your library to 4.0 version of KotlinTest: https://github.com/kotlintest/kotlintest/pull/1158

**Comment by simonenkoi** [comment]
@nlochschmidt can we merge it?

**Pull request merged**
