### PR TITLE
Add uuid validation method

### PR DESCRIPTION
**Pull request by vitorfec**
Adds a uuid validation function to avoid the need for a pattern on client code

### CODE REVIEW

**Comment by dhoepelman** [comment]
Needs to be looked at, preferably we have a good integration with `java.util.UUID` on the JVM

**Review by jillesvangurp — APPROVED** [review]
LGTM!

**Comment by dhoepelman** [comment]
It only uses existing regex `pattern()` right? So that should be fine multiplatform

**Comment by jillesvangurp** [comment]
true, in that case we should figure out the build issues

**Review by dhoepelman — APPROVED** [review]

**Comment by dhoepelman** [comment]
Thanks @vitorfec, even if it took 2 years :)

**Pull request merged**
